// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_KEY',
    appId: 'REPLACE_WITH_YOUR_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_ID',
    projectId: 'gonana-enhanced',
    authDomain: 'gonana-enhanced.firebaseapp.com',
    storageBucket: 'gonana-enhanced.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGXAVDypeNXNlmAdOMjr58HQUAvfJoR2k',
    appId: '1:609134697330:android:7dbbff56dfb8c2f3b4dbeb',
    messagingSenderId: '609134697330',
    projectId: 'gonana-v2',
    storageBucket: 'gonana-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_KEY',
    appId: 'REPLACE_WITH_YOUR_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_ID',
    projectId: 'gonana-enhanced',
    storageBucket: 'gonana-enhanced.appspot.com',
    iosClientId: 'REPLACE_WITH_YOUR_ID',
    iosBundleId: 'com.example.gonanaEnhanced',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'REPLACE_WITH_YOUR_KEY',
    appId: 'REPLACE_WITH_YOUR_ID',
    messagingSenderId: 'REPLACE_WITH_YOUR_ID',
    projectId: 'gonana-enhanced',
    storageBucket: 'gonana-enhanced.appspot.com',
    iosClientId: 'REPLACE_WITH_YOUR_ID',
    iosBundleId: 'com.example.gonanaEnhanced',
  );
}
